# Generated by Django 5.2.2 on 2025-06-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('isReleased', models.BooleanField(default=True)),
                ('reviews', models.JSONField(default=list)),
                ('cast', models.JSONField(default=list)),
            ],
        ),
    ]
