# Generated by Django 5.2.2 on 2025-06-11 14:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('isReleased', models.BooleanField(default=True)),
                ('reviews', models.JSONField(default=list)),
                ('cast', models.JSONField(default=list)),
            ],
        ),
    ]
