# Generated by Django 5.2.2 on 2025-06-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movierestapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='id',
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
