# Generated by Django 5.2.1 on 2025-06-22 17:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('artist_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=70)),
                ('artist_about', models.CharField(max_length=350)),
                ('artist_created', models.DateTimeField(auto_now_add=True)),
                ('artist_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StreamingPlatform',
            fields=[
                ('platform_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform_name', models.CharField(max_length=70)),
                ('platform_about', models.CharField(max_length=350)),
                ('platform_url', models.URLField()),
                ('platform_created', models.DateTimeField(auto_now_add=True)),
                ('platform_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentDetails',
            fields=[
                ('content_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_name', models.CharField(max_length=70)),
                ('content_description', models.CharField(max_length=350)),
                ('content_released', models.BooleanField(default=True)),
                ('content_created', models.DateTimeField(auto_now_add=True)),
                ('content_updated', models.DateTimeField(auto_now=True)),
                ('artists', models.ManyToManyField(blank=True, related_name='content', to='app.artists')),
                ('content_platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='app.streamingplatform')),
            ],
        ),
        migrations.CreateModel(
            name='ContentReviews',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_name', models.CharField(max_length=70)),
                ('review_body', models.CharField(max_length=350)),
                ('review_stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review_created', models.DateTimeField(auto_now_add=True)),
                ('review_updated', models.DateTimeField(auto_now=True)),
                ('review_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.contentdetails')),
                ('review_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('review_user', 'review_movie'), name='one_review_per_user')],
            },
        ),
    ]
