# Generated by Django 5.2.3 on 2025-06-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentreviews',
            name='review_average',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='contentreviews',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
