# Generated by Django 5.2.3 on 2025-06-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contentreviews_review_average_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentreviews',
            name='review_average',
        ),
        migrations.RemoveField(
            model_name='contentreviews',
            name='review_count',
        ),
        migrations.AddField(
            model_name='contentdetails',
            name='review_average',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='contentdetails',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
