# Generated by Django 5.2.3 on 2025-06-19 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_contentreviews_review_average_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentdetails',
            name='review_average',
        ),
        migrations.RemoveField(
            model_name='contentdetails',
            name='review_count',
        ),
    ]
